#database
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liXYHiPBHUHTDzJl
            client-secret: Ov23liXYHiPBHUHTDzJl
            scope:
              - read:user
              - user:email
            redirect-uri: https://www.un-veil.co.kr/login/oauth2/code/github
          kakao:
            client-id: 83890ddebb2f33cd5e086b43acc83284 # REST API key
            client-secret: jmplAYj5k8XWqSbMEjbGSkLs0qW9o6OM # Admin key
            authorization-grant-type: authorization_code
            redirect-uri: https://www.un-veil.co.kr/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 290551473190-echp48qonv5rhvdlmng4k6g9v36mg1nu.apps.googleusercontent.com
            client-secret: ${GOOGLE_SEC}
            scope:
              - email
              - profile
          naver:
            client-id: nPRhcAXxANCFXznitem9
            client-secret: 5nSEE9ROAt
            redirect-uri: https://www.un-veil.co.kr/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver
            scope:
              - name
              - email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com:
      unvail: debug
    org.springframework.security: error

server:
  port: 443
  ssl:
    enabled: true
    key-store: file:/home/app/unveilApp/cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: gkawjddn!1
    key-alias: unveil