#database
spring:
  application:
    name: unvail

  profiles:
    active: ${PROFILE:local}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3869924742be96fcd0743d5d1d173e04 # REST API key
            client-secret: K23G0ItPzWe34MkXKy65Naoci9YN6Tjn # Admin key
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  web:
    locale: ko_KR
    resources:
      static-locations:
        - classpath:/static/

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: static/**, templates/**

  ##mustache
  mustache:
    suffix: .html
    prefix: classpath:/templates/views/
    servlet:
      cache: false
      expose-request-attributes: true

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&reWriteBatchedInserts=true&tcpKeepAlive=true
    username: postgres.aekmugwewfkvepikdjib
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2

  #openai
  ai:
    openai.api-key: ${OPENAPI_API_KEY}
    vertex.ai.gemini.project-id: ${GEMINI_PROJECT_ID}
    vertex.ai.gemini.location: ${GEMINI_LOCATION}

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com:
      unvail: debug
    org.springframework.security: DEBUG

Jasypt:
  encryptor:
    bean: jasyptStringEncryptor

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true