#database
spring:
  application:
    name: unvail

  profiles:
    active: ${PROFILE:local}

  web:
    locale: ko_KR
    resources:
      static-locations:
        - classpath:/static/

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: static/**, templates/**

  ##mustache
  mustache:
    suffix: .html
    prefix: classpath:/templates/views/
    servlet:
      cache: false
      expose-request-attributes: true

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&reWriteBatchedInserts=true&tcpKeepAlive=true
    username: postgres.aekmugwewfkvepikdjib
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2

  #openai
  ai:
    openai.api-key: ${OPENAPI_API_KEY}
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.9
          top-p: 0.95
          max-tokens: 1200
          presence-penalty: 0.6
          frequency-penalty: 0.3
    vertex.ai.gemini.project-id: ${GEMINI_PROJECT_ID}
    vertex.ai.gemini.location: ${GEMINI_LOCATION}

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com:
      unvail: debug
    org.springframework.security: DEBUG

Jasypt:
  encryptor:
    bean: jasyptStringEncryptor

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true