#database
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liuQ1GM1L0veh6FE
            client-secret: 88159686f6a131c89068f70dfa2cb0c1688ccb63
            scope:
              - read:user
              - user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          kakao:
            client-id: 3869924742be96fcd0743d5d1d173e04 # REST API key
            client-secret: K23G0ItPzWe34MkXKy65Naoci9YN6Tjn # Admin key
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 290551473190-tc26p1unbjmkm1carj12hgs252m7404p.apps.googleusercontent.com
            client-secret: ${GOOGLE_SEC}
            scope:
              - email
              - profile
          naver:
            client-id: oXRm8hf6bLdqspBotua5
            client-secret: zMAqdgWodi
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver
            scope:
              - name
              - email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com:
      unvail: debug
    org.springframework.security: DEBUG
server:
  port: 8080

portone:
  api-url: https://api.portone.io
  kakao-sec-key: Kuoag87lxkkoFVDUdQXkWTI8eYKGGlet3rotHtJxbd2GI3ZzIQzIxTl1lQovUq268UviJTekrzXZccgc
  store-id: store-d634ec72-0de5-4990-84fc-f2aa1450b88b