#database
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3869924742be96fcd0743d5d1d173e04 # REST API key
            client-secret: K23G0ItPzWe34MkXKy65Naoci9YN6Tjn # Admin key
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 290551473190-tc26p1unbjmkm1carj12hgs252m7404p.apps.googleusercontent.com
            client-secret: ${GOOGLE_SEC}
            scope:
              - email
              - profile
          naver:
            client-id: oXRm8hf6bLdqspBotua5
            client-secret: zMAqdgWodi
            redirect-uri:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: naver
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: <https://nid.naver.com/oauth2.0/authorize>
            token-uri: <https://nid.naver.com/oauth2.0/token>
            user-info-uri: <https://openapi.naver.com/v1/nid/me>
            user-name-attribute: id
logging:
  level:
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com:
      unvail: debug
    org.springframework.security: DEBUG
server:
  port: 8080